### ISSUE TITLE
Fio-plot and bench-fio supports Fio built-in client-server mechanism

### ISSUE THREAD

**Issue by louwrentius** [louwrentius/fio-plot#102]
## bench-fio
bench-fio now supports the [client/server mechanism that is built-in for fio](https://fio.readthedocs.io/en/latest/fio_doc.html#client-server).  This means that the bench-fio tool can run the same benchmark across one or more remote hosts (servers) that run fio in server mode (fio --server) and collect the output locally.

Another huge change under-the-hood which may be of less interest is that bench-fio _no longer_ uses environment variables and fio-templates to run fio. Instead, bench-fio generates fully populated fio job files based on either user-specified INI file or command-line parameters. This is partially to support the client/server mechanism.

## fio-plot 
The client-server benchmark data is either stored as JSON output or .log files containing traces. Fio-plot can parse those files and plot charts as usual.

![TEST-NFS-CLIENTS_2023-03-31_131125_Sl](https://user-images.githubusercontent.com/1312044/229105286-846149c3-5e0e-45a5-9973-bd367f70322a.png)
![image][demo02]
![image][demo01]

[demo01]: https://louwrentius.com/static/images/fio-client-server-demo.png
[demo02]: https://louwrentius.com/static/images/fio-client-server-demo-2.png

**Comment by louwrentius** [comment]
> Is this reasonable?
> 
> 
> 
> I think we can add a new parameter like '--all-clients' to draw 'All clients' data only.

I will take a look - no timeline - I have some bugs to fix

**Comment by louwrentius** [comment]
@assange0 wout it be possible to share your JSON output with me, either here or through louwrentius%gmail.com?

**Comment by assange0** [comment]
> @assange0 wout it be possible to share your JSON output with me, either here or through louwrentius%gmail.com?

Here it is: [nfsv3_randread_9v1.tar.gz](https://github.com/louwrentius/fio-plot/files/11120819/nfsv3_randread_9v1.tar.gz)

**Comment by louwrentius** [comment]
So what you want is already possible:

`fio-plot -i nfsv3_randread_9v1/4k/ -T "TEST NFS CLIENTS" -l -r randread -d 1 8 32 128 --include-hosts "All clients"`

![TEST-NFS-CLIENTS_2023-03-31_131125_Sl](https://user-images.githubusercontent.com/1312044/229105286-846149c3-5e0e-45a5-9973-bd367f70322a.png)

Let me know if this works for you.

**Comment by assange0** [comment]
> Let me know if this works for you.

I run that command and the get the graph:
![TEST-NFS-CLIENTS_2023-03-31_211844_wm](https://user-images.githubusercontent.com/8962458/229133398-090f8e8f-ad43-4dc9-9869-b1dad9955715.png)

Software info:
- Ubuntu 22.04
- Python 3.10.6
- fio-plot 1.1.2

**Comment by louwrentius** [comment]
The issue has been resolved, 1.1.3 should be fine.
