### ISSUE TITLE
fio-plot only shows up to 60s of data

### ISSUE THREAD

**Issue by johnramsden** [louwrentius/fio-plot#103]
Unless I'm mistaken it's not possible to increase the length of time shown in the graphs? I do not see any flags available. When I create a plot it only shows 60 seconds, I would like to have a graph that covers the entire bench.

**Comment by louwrentius** [comment]
Hi, if you look at the log files does it contain more data beyond 60 seconds? How did you benchmark?Can you share the output files? Maybe privately via louwrentius at gmail.comRegardsOn 14 Mar 2023, at 03:19, John ***@***.***> wrote:﻿
Unless I'm mistaken it's not possible to increase the length of time shown in the graphs? I do not see any flags available. When I create a plot it only shows 60 seconds, I would like to have a graph that covers the entire bench.

**Comment by johnramsden** [comment]
Hi Lou.

I mostly followed some of the readme examples. And when I look at them they also have 60 seconds of data. My experiment took about 50 minutes, so I was hoping to see 50 minutes of graph. Eventually I will be adding multiple tests to the graph (i'm not sure how this will work if they are slightly different duration).

Bench:

```
./venv/bin/bench-fio -t file -d /disktest/test -s "219" --mode randwrite --output 4096 --destructive
```

plot:

```
fio-plot -i 4096/test/4k -T "Comparing IOPs performance of multiple cluster sizes" -g -t iops -r randwrite --xlabel-parent 0
```

Graph:

![Comparing-IOPs-performance-of-multiple-cluster-sizes_2023-03-13_190632_gI](https://user-images.githubusercontent.com/8735102/225123506-93dee931-c53b-47fd-9ffb-f0adbb7821f0.png)

Logs: [4096.tar.gz](https://github.com/louwrentius/fio-plot/files/10973265/4096.tar.gz)

**Comment by louwrentius** [comment]
It seems that you ran bench-fio with default parameters. This means that it will run with queue depth 1 2 4 8 16 32 64 and also the same for numjobs so 7 x 7 is 49 tests at 1 minute each (default runtime) which matches how long your test ran.

So now I'm able to generate this chart for purely IOPs:

`~/projects/fio-plot/bin/fio-plot -i 4k/ -T "Test Plot" -g -r randwrite -t iops -d 1 2 4 8 16 32 64 `

![Test-Plot_2023-03-14_222324_NF](https://user-images.githubusercontent.com/1312044/225139588-bdb9c51d-613f-4aec-9d30-a73495f0eed3.png)

And this chart for latency: 

`~/projects/fio-plot/bin/fio-plot -i 4k/ -T "Test Plot" -g -r randwrite -t lat -d 1 2 4 8 16 32 64 `

![Test-Plot_2023-03-14_222437_tw](https://user-images.githubusercontent.com/1312044/225139721-a3e27c5e-7f6d-4d80-acff-5a1102abd405.png)

Or we can plot it like this:

`~/projects/fio-plot/bin/fio-plot -i 4k/ -T "Test Plot" -l -r randwrite`

![Test-Plot_2023-03-14_222510_cb](https://user-images.githubusercontent.com/1312044/225139883-0d42b021-48ab-44e1-8fbe-4670eb8c81e4.png)

**Comment by johnramsden** [comment]
Thank you! Ill let you know how it goes.

**Comment by johnramsden** [comment]
@louwrentius Thanks! Great results!
![Comparing-IOPs-performance-of-multiple-cluster-sizes_2023-03-14_185615_DX](https://user-images.githubusercontent.com/8735102/225186208-b7770e6a-3672-4cad-82be-9491725d3c19.png)

**Comment by louwrentius** [comment]
Thanks John, seems like very interesting results!
