### ISSUE TITLE
Version 1.1.3 reintroduces #106

### ISSUE THREAD

**Issue by willgorman** [louwrentius/fio-plot#109]
With version 1.1.3 bench-fio appears to only be generating a fio test run for the first permutation of parameters rather than all of them.  Version 1.1.2 does generate all permutations as expected.  This looks like it may be the same issue that was originally fixed in #106   

## Command
Command: `bench-fio --target . --type directory --size 1G --iodepth 1 16 --numjobs 1 2 --b 4k 16k --mode randrw --output example --rwmixread 90 `

## 1.1.3 Result

![CleanShot 2023-04-10 at 15 58 03](https://user-images.githubusercontent.com/49793/230997555-e60a9578-9d69-4770-9034-56ad10493835.png)

## 1.1.2 Result

![CleanShot 2023-04-10 at 16 01 55](https://user-images.githubusercontent.com/49793/230998272-5d455930-3a70-4517-966d-5ed6f3764db2.png)

**Comment by louwrentius** [comment]
I may have been making some mistakes with git, so I will investigate

**Comment by louwrentius** [comment]
![image](https://user-images.githubusercontent.com/1312044/231017486-3737a887-c369-4d97-8a87-4323e2f14924.png)

**Comment by willgorman** [comment]
Thanks!  I tried 1.1.4 and it's working the same as 1.1.2 👍
