### ISSUE TITLE
Could we develop a test suite for "Solid State Storage (SSS) Performance Test Specification (PTS)"

### ISSUE THREAD

**Issue by jackeichen** [louwrentius/fio-plot#115]
louwrentius,

The SNIA has developed methods which enable manufacturers to set, and customers to compare, the performance specifications of Solid State Storage devices, which are evolving with the state of the technology. These specifications define a set of device level tests and methodologies which enable comparative testing of SSS devices for Enterprise and Client systems.

I know this will be a huge jobs to do this. Would you like to do a future feature design for "Solid State Storage (SSS) Performance Test Specification (PTS)".
As fio-plot is a very  suitable tool: it can both define an IO workload in bench-fio, and plot it in fio-plot.

**Comment by louwrentius** [comment]
Hi, thanks for your suggestion.

I'm quite sure that bench-fio in combination with custom fio jobs (you would specify) would already be able to run the tests.

It sounds like fio-plot would need to output something that fits (industry standard) reporting? That would indeed likely take a lot of work as you alluded to. Maybe you can clarify it a bit more?

Given the context, I would like to be paid for the work, just to set expectations.

**Comment by louwrentius** [comment]
I've not seen any updates on this so I've closed the issue.
