### ISSUE TITLE
unicode error on benchmark script

### ISSUE THREAD

**Issue by nwilson666** [louwrentius/fio-plot#12]
no matter what combinations of options I try on the benchmark script I get this error:

Traceback (most recent call last):
  File "./bench_fio", line 385, in <module>
    main()
  File "./bench_fio", line 378, in main
    display_header(settings, tests)
  File "./bench_fio", line 297, in display_header
    print(f"\u2588" * (fl + width))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-77: ordinal not in range(128)

Any ideas? I'm running the script on a rhel7.7 server.

**Comment by nwilson666** [comment]
#    print(f"�~V~H" * (fl + width))

It appears that my system doesnt like the � characters - if I comment out the lines with that one the script works.

**Comment by louwrentius** [comment]
It seems my attempt to make things 'pretty' just breaks things.
I'll use another character, thanks for the feedback.

**Comment by nwilson666** [comment]
looks like export PYTHONIOENCODING=UTF-8 fixes it. 
might have been an issue with me running it as root .. but you kind of need to run a root for fio testing..

**Comment by louwrentius** [comment]
I've changed the actual character a bit. The latest master should work without your 'export'. 
██████████████████████████████████████████████████████████████████████████████
                        +++ Fio Benchmark Script +++

Job template:                  ./fio-job-template.fio
I/O Engine:                    libaio
Number of benchmarks:          8
Estimated duration:            0:08:00
Devices to be tested:          /root/tmp
Test mode (read/write):        randread randwrite
IOdepth to be tested:          1
NumJobs to be tested:          1 2 4 8
Block size(s) to be tested:    4k
Time per test (s):             60
File size:                     20G

██████████████████████████████████████████████████████████████████████████████

**Comment by nwilson666** [comment]
Hi it still does this:

Traceback (most recent call last):
  File "./bench_fio", line 392, in <module>
    main()
  File "./bench_fio", line 385, in main
    display_header(settings, tests)
  File "./bench_fio", line 304, in display_header
    print(f"{blockchar}" * (fl + width))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-77: ordinal not in range(128)

Until I run export PYTHONIOENCODING=UTF-8, then it appears to be working - although with an issue, I ran it with the options below and it wrote the iotest.0.0 100g file into the local directory instead of in /var/tmp.

 ls -l
total 104857868
-rw-r--r-- 1 root root         5993 Apr 22 15:42 README.md
drwxr-xr-x 2 root root         4096 Apr 22 15:02 __pycache__
-rwxr-xr-x 1 root root         1164 Apr 22 15:42 bench-fio.sh
-rwxr-xr-x 1 root root        14619 Apr 22 15:42 bench_fio
lrwxrwxrwx 1 root root           11 Apr 22 16:15 bench_fio.py -> ./bench_fio
-rwxr-xr-x 1 root root         1538 Apr 22 15:42 bench_fio_test.py
-rw-r--r-- 1 root root          420 Apr 22 15:42 fio-job-template.fio
-rw-r--r-- 1 root root 107374182400 Apr 22 16:40 iotest.0.0
-rw-r--r-- 1 root root            6 Apr 22 15:42 requirements.txt
drwxr-xr-x 4 root root         4096 Apr 22 16:36 spice_test


./bench_fio --target /var/tmp --type folder --mode randread randwrite -b 4k -s 100g --output spice_test --iodepth 1 --numjobs 1
██████████████████████████████████████████████████████████████████████████████
                        +++ Fio Benchmark Script +++

Job template:                  ./fio-job-template.fio
I/O Engine:                    libaio
Number of benchmarks:          2
Estimated duration:            0:02:00
Devices to be tested:          /var/tmp
Test mode (read/write):        randread randwrite
IOdepth to be tested:          1
NumJobs to be tested:          1
Block size(s) to be tested:    4k
Time per test (s):             60
File size:                     100g

██████████████████████████████████████████████████████████████████████████████
 100% |█████████████████████████|   [0:03:58, 0:00:00]-]

you also might want to just add some stuff telling people to set export PYTHONIOENCODING=UTF-8 if running as root on centos or rhel.

**Comment by louwrentius** [comment]
Thanks for the feedback, I'm going to use a different character because it's just for cosmetic reasons. This is not important enough to ask people to run the export. 

What worries me more is your issue with the 'directory' option. I'll make a separate issue for that.

**Comment by louwrentius** [comment]
I believe I've fixed both issues. Issue #13  is also fixed but please beware that I've made the type now 'directory' not 'folder' to be consistent with linux/fio naming.

**Comment by nwilson666** [comment]
Bad news,  it's still erroring unless i use the export.

Traceback (most recent call last):
  File "./bench_fio", line 390, in <module>
    main()
  File "./bench_fio", line 385, in main
    run_benchmarks(settings, tests)
  File "./bench_fio", line 119, in run_benchmarks
    for benchmark in ProgressBar(benchmarks):
  File "./bench_fio", line 150, in ProgressBar
    sys.stdout.write('\r'+barStr+activity[nn % 4]+timeStr)
UnicodeEncodeError: 'ascii' codec can't encode character '\u258e' in position 8: ordinal not in range(128)

Thanks for your work on this , its useful to have a wrapper and plot generator for FIO.

**Comment by louwrentius** [comment]
Thanks for sticking this out and testing. It also seems to be affected by the progress bar code.  I'm going to try and get a RH iso so I can reproduce this issue and warn the user. I may actually go with your advice about just exporting the environment variable.

**Comment by louwrentius** [comment]
I've incorporated a check based on your PYTHONIOENCODING=UTF-8 tip. If PYTHONIOENCODING=UTF-8 everything should be fine but if it's set to ascii, you'll get a warning + explanation. Would you mind testing this on your end?
