### ISSUE TITLE
displaying system time

### ISSUE THREAD

**Issue by peterwi** [louwrentius/fio-plot#128]
Hi, thanks for the tool,
Is there any way to be able to display system time on the charts?

**Comment by peterwi** [comment]
That would also work, but I was thinking of being able to see timestamps on the x axis on the diagram

**Comment by louwrentius** [comment]
Hi Peter, 

Thanks, that is not possible at this time. If you want can you explain the use case? Would the -g style graph not be of any help (relative time)?
