### ISSUE TITLE
Specified target folder for benchmarking is not actually used by FIO

### ISSUE THREAD

**Issue by louwrentius** [louwrentius/fio-plot#13]
although with an issue, I ran it with the options below and it wrote the iotest.0.0 100g file into the local directory instead of in /var/tmp.

ls -l
total 104857868
-rw-r--r-- 1 root root 5993 Apr 22 15:42 README.md
drwxr-xr-x 2 root root 4096 Apr 22 15:02 pycache
-rwxr-xr-x 1 root root 1164 Apr 22 15:42 bench-fio.sh
-rwxr-xr-x 1 root root 14619 Apr 22 15:42 bench_fio
lrwxrwxrwx 1 root root 11 Apr 22 16:15 bench_fio.py -> ./bench_fio
-rwxr-xr-x 1 root root 1538 Apr 22 15:42 bench_fio_test.py
-rw-r--r-- 1 root root 420 Apr 22 15:42 fio-job-template.fio
-rw-r--r-- 1 root root 107374182400 Apr 22 16:40 iotest.0.0
-rw-r--r-- 1 root root 6 Apr 22 15:42 requirements.txt
drwxr-xr-x 4 root root 4096 Apr 22 16:36 spice_test

./bench_fio --target /var/tmp --type folder --mode randread randwrite -b 4k -s 100g --output spice_test --iodepth 1 --numjobs 1
██████████████████████████████████████████████████████████████████████████████
+++ Fio Benchmark Script +++

Job template: ./fio-job-template.fio
I/O Engine: libaio
Number of benchmarks: 2
Estimated duration: 0:02:00
Devices to be tested: /var/tmp
Test mode (read/write): randread randwrite
IOdepth to be tested: 1
NumJobs to be tested: 1
Block size(s) to be tested: 4k
Time per test (s): 60
File size: 100g

██████████████████████████████████████████████████████████████████████████████
100% |█████████████████████████| [0:03:58, 0:00:00]-]

**Comment by nwilson666** [comment]
It's now using the correct target folder. I believe this one can be closed.

**Comment by louwrentius** [comment]
Thank you for verifying.
