### ISSUE TITLE
fio-plot

### ISSUE THREAD

**Issue by NIKREB23** [louwrentius/fio-plot#130]
Hi, now iam able to get the out put file but still it throwing this error 

(fio-plot) ubuntu@host1:~/fio$ fio-plot /home/ubuntu/fio/fio-plot.ini -T "surya" -N -r randread -O /path/to/output-directory/
type
colors

 Saving to file /home/ubuntu/fio/fio-plot/surya

Traceback (most recent call last):
  File "/home/ubuntu/fio/fio-plot/bin/fio-plot", line 11, in <module>
    load_entry_point('fio-plot==1.1.12', 'console_scripts', 'fio-plot')()
  File "/home/ubuntu/fio/fio-plot/lib/python3.8/site-packages/fio_plot/__init__.py", line 39, in main
    routing_dict[graphtype]["function"](settings, data)
  File "/home/ubuntu/fio/fio-plot/lib/python3.8/site-packages/fio_plot/fiolib/bar2d.py", line 184, in chart_2dbarchart_jsonlogdata
    supporting.save_png(settings, plt, fig)
  File "/home/ubuntu/fio/fio-plot/lib/python3.8/site-packages/fio_plot/fiolib/supporting.py", line 474, in save_png
    write_png_metadata(savename, settings)
  File "/home/ubuntu/fio/fio-plot/lib/python3.8/site-packages/fio_plot/fiolib/supporting.py", line 478, in write_png_metadata
    targetImage = PngImageFile(filename)
  File "/home/ubuntu/fio/fio-plot/lib/python3.8/site-packages/PIL/ImageFile.py", line 105, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/fio/fio-plot/surya'
[fio_results3.json](https://github.com/louwrentius/fio-plot/files/13740046/fio_results3.json)
[fio_results3.json](https://github.com/louwrentius/fio-plot/files/13740056/fio_results3.json)
![nikhil](https://github.com/louwrentius/fio-plot/assets/105602461/05e4ab3c-10b3-4eb8-a393-02293be157eb)
![surya](https://github.com/louwrentius/fio-plot/assets/105602461/8621444f-8081-46c6-8ac7-e70005b94aae)

**Comment by NIKREB23** [comment]
[[graphtype].txt](https://github.com/louwrentius/fio-plot/files/13740074/graphtype.txt)

**Comment by louwrentius** [comment]
Thank you for sharing the info, I'll have to take a look in the coming days

**Comment by NIKREB23** [comment]
yah please if any lead let me know : )

**Comment by louwrentius** [comment]
- Please use either the INI format *or* command line options, I've not even tested mixing them
- Your command line output parameter should point to a file not just a directory (ini seems ok)
- Your .json file seems to only contain one test data sample so there's not much to graph

I've renamed your json file like this and pointed fio-plot input dir to the 4k folder.

`$ tree data/
data/
└── vda
    └── 4k
        └── randread-16-4.json
`
[fio-plot.ini.txt](https://github.com/louwrentius/fio-plot/files/13761691/fio-plot.ini.txt)

Maybe the included tool 'bench-fio' may help create more meaningfull results, but that's up to you.

**Comment by NIKREB23** [comment]
thank you so much end up with good result : )
