### ISSUE TITLE
Missing Path in python function "write_fio_job_file" 

### ISSUE THREAD

**Issue by Tabimeter** [louwrentius/fio-plot#144]
Hi,
i had a Problem with bench_fio where it said "Failed to write temporary Fio job file at tmpjobfile".
I searched the string and its in file generatefio.py . 
When "tmpjobfile" is changed to "{tmpjobfile}" it prints out the path correctly.
Somehow there was already a file with the same name in the /tmp folder (tried a few settings before for bench_fio and terminated often with ctrl-C ), after deleting the file in /tmp everything worked as expected.

Greetings

**Comment by louwrentius** [comment]
Thanks for the report!
