### ISSUE TITLE
can't set --duration

### ISSUE THREAD

**Issue by peterwi** [louwrentius/fio-plot#15]
`[root@latpoc17 benchmark_script]# ./bench_fio --target /mnt/peter --type directory --size=2G -e=posixaio --template fio-job-template.fio  --iodepth 8  --numjobs 8 --mode read --duration 360 --output WEKA
　
Traceback (most recent call last):
  File "./bench_fio", line 461, in <module>
    main()
  File "./bench_fio", line 454, in main
    display_header(settings, tests)
  File "./bench_fio", line 362, in display_header
    duration = calculate_duration(settings, tests)
  File "./bench_fio", line 323, in calculate_duration
    duration = str(datetime.timedelta(seconds=duration_in_seconds))
`

**Comment by justinas-marozas** [comment]
Looks like a bug to me. `get_arguments` function does not specify a type for the `--duration` argument, so `argparse` just leaves it as a string. The value captured from `--duration 360` therefore is `'360'` and not `360`. Adding argument `type=int` to the `add_argument` call fixed it for me.

**Comment by louwrentius** [comment]
Thank you for the report!
