### ISSUE TITLE
bench_fio uses os.path.isfile to check for device targets

### ISSUE THREAD

**Issue by bureado** [louwrentius/fio-plot#16]
From https://github.com/louwrentius/fio-plot/blob/master/benchmark_script/bench_fio#L103 it seems that `bench_fio` uses Python's `os.path.isfile()` to test if a certain target device is valid.

However, at least on Python 3.8.2 and Ubuntu 20.04 LTS (focal) this function returns `False` for any non-regular file, like block devices.

A workaround to get the script going is to use `os.path.exists` but a more durable solution would be to use `pathlib`, for example:

```
pathlib.Path('/dev/sda').is_block_device()
```

**Comment by louwrentius** [comment]
Thanks for the report and proposed solution.

**Comment by louwrentius** [comment]
I have used the pathlib library in the latest version in the 'master' branch. Would you mind trying it out and giving some feedback?
