### ISSUE TITLE
Running fio__plot - no files found matching parameter "randrw"

### ISSUE THREAD

**Issue by kvietmeier** [louwrentius/fio-plot#18]
I have both FIO and fio-plot installed
FIO: fio-3.19-48-g3966
fio_plot - latest version cloned a few days ago
Centos:  CentOS Linux release 7.7.1908 (Core)

I run the following:
` ./bench_fio --target /mnt/afs-nfsv4 --type directory --size 5G --template fio-job-template.fio  --iodepth 1 8 16 --numjobs 16 --mode randrw --output NFS_TEST --readmix 75 90`

`./fio_plot -i ../benchmark_script/NFS_TEST/afs-nfsv4/randrw90/4k -T "Test" -g -r randrw -t iops lat -d 1 8 16 -n 1`

The directory is populated with json and .log files......
`root@nfsv4test01 (afs-nfsv4)# tree -L 3
├── randrw75

│   └── 4k
│       ├── randrw-1-16.json
│       ├── randrw-16-16.json
│       ├── randrw-8-16.json
│       ├── randrw-iodepth-16-numjobs-16_bw.10.log
│       ├── randrw-iodepth-16-numjobs-16_bw.11.log
│       ├── randrw-iodepth-16-numjobs-16_bw.12.log
│       ├── randrw-iodepth-16-numjobs-16_bw.13.log
│       ├── randrw-iodepth-16-numjobs-16_bw.14.log
│       ├── randrw-iodepth-16-numjobs-16_bw.15.log
│       ├── randrw-iodepth-16-numjobs-16_bw.16.log
│       ├── randrw-iodepth-16-numjobs-16_bw.1.log`

But I consistently get this - 
`No log files found that matches the specified parameter randrw`

I checked the json, randrw is in there.

Wondering what I might be missing.

**Comment by louwrentius** [comment]
Thanks for your report, I'm running a simulation to determine if I can reproduce the issue.

**Comment by louwrentius** [comment]
It was actually quite simple: you mixed -n and -d parameters. I've made the error message more descriptive. (pushed to master). 
![Test-2020-05-08_223458](https://user-images.githubusercontent.com/1312044/81447491-0049d680-917d-11ea-8083-a8b0327bdc20.png)

**Comment by kvietmeier** [comment]
Is it the order?

**Comment by kvietmeier** [comment]
Thanks!  It was the order.  BTW - I copied that command directly from the examples.

**Comment by louwrentius** [comment]
No, I was wrong FYI: if you use -d 1 8 16 and -n 16 instead of -n 1 it works. I was wrong about the order.
