### ISSUE TITLE
Consider adding choice of direct/buffered IO as parameter

### ISSUE THREAD

**Issue by itzsimpl** [louwrentius/fio-plot#19]
Consider adding
```
    ag.add_argument(
        "--direct", help=f"Override the default IO mode for benchmark \
            (default: {settings['direct']})", type=int, default=settings['direct'])
```
at line 251 of `benchmark_script/bench_fio`.

For example ZFS does not support direct IO mode (see https://github.com/openzfs/zfs/issues/224), so in order to run tests on ZFS one needs to be able to disable it.

**Comment by louwrentius** [comment]
Done, commited to master branch.
