### ISSUE TITLE
Unable to recreate graph

### ISSUE THREAD

**Issue by itzsimpl** [louwrentius/fio-plot#20]
I am trying to recreate the line graph for a comparison of two setups, like in the case of RAID10 vs RAID5 in your case, but I seem to be unable to obtain the same output. 

Following your example
```
./fio_plot -i ../../RAID10 ../../RAID5 -T "Comparing RAID 10 vs. RAID 5 on 10,000 RPM Drives" -s https://louwrentius.com -g -r randread -t iops lat -d 8 -n 1 
```
The command I'm running is:
```
./fio_plot -i results/A/4k/ results/B/4k/  -T "RAIDZ2 6+6 vs RAIDZ2 6+6+LOG+CACHE" -g -r randread -t iops lat -d 8 -n 1
```

but the output shows only data for one and no legend at the bottom. 

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/4784070/85945739-1d5e8280-b940-11ea-9a18-8a4548c0b578.png">

Am I doing something wrong?

**Comment by louwrentius** [comment]
I’ve seen this before with a too old version of Matplotlib. I should check for this. 3+ is mandatory.

**Comment by itzsimpl** [comment]
OK, I've updated matplot. Perhaps consider adding a minimal version in requirements.txt file. Now there's a legend at the bottom, but still only one plot. 

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/4784070/85946688-6fa2a200-b946-11ea-9770-9dce56a825d4.png">

**Comment by louwrentius** [comment]
Would it be acceptable to you if you would share those two folders? I'm
wondering what the difference is. Do the results of the folder data that is
missing render if you only point to that folder?

Op zo 28 jun. 2020 om 13:52 schreef Iztok Lebar Bajec <
notifications@github.com>:

**Comment by itzsimpl** [comment]
If I revers the order of the folders in the command
```
./fio_plot -i results/B/4k/ results/A/4k/  -T "RAIDZ2 6+6 vs RAIDZ2 6+6+LOG+CACHE" -g -r randread -t iops lat -d 8 -n 1
```
I get

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/4784070/85947017-8d710680-b948-11ea-88da-da61da30e7e5.png">

If I plot just folder A, I get
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/4784070/85947050-b7c2c400-b948-11ea-8f7c-59b5b44eca08.png">

If I plot jus folder B, I get
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/4784070/85947064-cc06c100-b948-11ea-8727-a5642ca0c18b.png">

**Comment by louwrentius** [comment]
Wow, that seems like a crazy fat bug. It seems that the results are just
added together, that's embarrassing.
I would really have a copy of the test results but if that's not possible
let me know.

In the mean time I'll try and reproduce this issue with my own test data.

Op zo 28 jun. 2020 om 14:09 schreef Iztok Lebar Bajec <
notifications@github.com>:

**Comment by louwrentius** [comment]
I think I solved the issue: please use this command:

./fio_plot -i results/A results/B -T "RAIDZ2 6+6 vs RAIDZ2 6+6+LOG+CACHE"
-g -r randread -t iops lat -d 8 -n 1

This should work perfectly. I should document this better.

Op zo 28 jun. 2020 om 13:13 schreef Iztok Lebar Bajec <
notifications@github.com>:

**Comment by louwrentius** [comment]
I've also updated the documentation, let me know if this worked for you.

**Comment by itzsimpl** [comment]
Sorry, but I don't see any difference with the command I was running, and the output is the same. You can find the data here https://we.tl/t-LmhO98ksLl.

**Comment by louwrentius** [comment]
Thank you for sharing the data. I was wrong about the solution. This is what you have to do:
Rename the 4K folders in each test folder to a distinct name, such as 'A' and 'B'. This is the result I generated. 

![image](https://user-images.githubusercontent.com/1312044/85948989-4db01c00-b954-11ea-95c7-fc3c9893766c.png)

I will update my docs again for this.

**Comment by itzsimpl** [comment]
Thank you, this works, but it does require me to change the data folders produced by the benchmark. In this view, consider changing the function `return_folder_name()` to return the absolute path instead of the lowest level folder (basename). If this does not mess up other things. I bet that when issuing comparisons, most users will have at least one upper level folder that is different. In my case the issue arises since your data structure has a parameter named `directory`, which in both cases has the value of `4k`.

**Comment by louwrentius** [comment]
Yes, this is a valid criticism. I would opt to use the basename + one folder up the path, configurable with an extra command line parameter. The entire path would mess up the legend.

Thank you for your cooperation.

**Comment by itzsimpl** [comment]
Perhaps add the possibility to specify what to print in the legend (and use that as part of the title)?

**Comment by itzsimpl** [comment]
FYI: There's another simple solution; using softlinks create links that point to to folders of interest and have the name you want to be printed out in the legend. Then you can run the command using softlinks and everything will work fine as it is.

**Comment by louwrentius** [comment]
Thank you, I think that’s a reasonable approach and it saves me from adding complexities.

The symlinks can have a nice name without changeing the source data folders. That should be something I should put in the documentation.

Would that be suffient or is there something else that’s not covered by this approach?

**Comment by itzsimpl** [comment]
I haven't tested it on Windows, but on Linux it's a good workaround. Mind though that, yes, it saves you from adding complexities to the code, but in a way it ads complexities to the user guide. 

Perhaps you should still consider adding configurable parameters for labels. The code in the background could on startup create temporary softlinks using the labels and point them to the provided directories, generate the plots, and remove the softlinks once the plot is finished. This way there'll be a minimal amount of changes to be made to the code.

**Comment by louwrentius** [comment]
Ok I see your point, I will take it into account. When I have time available I will try and fix this issue. Feel free to leave this issue open until I implement a better solution.

**Comment by Nathan-K-Public** [comment]
You may already know now, but bug is in `def get_unique_directories(dataset):` in `dataimporty.py`. It only uses relative path name, both of which are `4k` for both runs. Thus both datasets are merged. I also used softlink method to workaround.

Add `pprint.pprint(dataset)` in this function to visualize.

**Comment by louwrentius** [comment]
I have created a new branch issue20 in which I have created a more user-friendly although still a bit cumbersome solution to this issue. 

```
If you use the bench_fio tool to generate benchmark data, you may notice that you end up with folders like:

    IBM1015/RAID10/4k
    IBM1015/RAID5/4k

Those parent folders are used to distinguish and identify the lines from each other. The labels are based on the parent folder names as you can see in the graph. By default, we use only one level deep, so in this example only RAID10 or RAID5 are used. If we want to include the folder above that (IBM1015) we use the --label-depth parameter like so:

    fio_plot -i ./IBM1015/RAID10/4k/ ./IBM1015/RAID5/4k/ -T "Comparing RAID 10 vs. RAID 5 on 10,000 RPM Drives" -s https://louwrentius.com -g -r randread -t iops lat -d 8 -n 1 -w 1 --label-depth 1
```

I will push this to master shortly.

**Comment by louwrentius** [comment]
I believe this issue is now resolved with the latest commit.

https://github.com/louwrentius/fio-plot/commit/1ef0089c25f3582f8fbb2e7df8971441a7365a55
