### ISSUE TITLE
Enhancement for comparing different filesystem ?

### ISSUE THREAD

**Issue by Martins3** [louwrentius/fio-plot#21]
fio-plot can compare bw, iops and lat at different iodepth, numjobs, read/write mode, etc.

I think maybe we can use it to compare different filesystems. This is my plan:
1. add a new option named `--filesystem`
2. if the `--type=device` and `--filesystem=ext4 btrfs xfs`, for every filesystem
    1. unmount the device 
    2. mkfs
    3. mount device
    4. run fio
3. add a new table to show the data.

If the idea is acceptable, I will work on a pull request for it.

**Comment by louwrentius** [comment]
Thanks for the suggestion, I'm OK with it and will merge.

**Comment by Martins3** [comment]
![gg_2020-07-25_210113](https://user-images.githubusercontent.com/16731244/88457720-344eb100-cebb-11ea-9e7a-1d1acbde8f7f.png)

Hi, there is a small demo, but I still need some time to complete.

**Comment by Martins3** [comment]
3D chart now is completed too.
![fs](https://user-images.githubusercontent.com/16731244/88479273-71c94200-cf80-11ea-85b7-d6ef8f609e6f.png)

**Comment by louwrentius** [comment]
Ok that’s awesome! Also interesting test result btw.

**Comment by Martins3** [comment]
This is just a simple test with  `--size=100m`, I will do a more reliable test in a few days and share it, before that I have to understand the code related to log

**Comment by louwrentius** [comment]
I've started the work to make some significant improvements to fio-plot, if you have any code to share this would be a good time. If not, please note that the code base is changing significantly and that you also may have to do some significant rework.

**Comment by Martins3** [comment]
Thanks for your attention. I found myself not familiar with python and matplotlib. I tried my best to make it work but failed to write clean [code](https://github.com/Martins3/fio-plot). I will keep watching this great project and learn something more before making a contribution.
