### ISSUE TITLE
Support sequential mix read write ?

### ISSUE THREAD

**Issue by Martins3** [louwrentius/fio-plot#22]
Both of benchmark_script and plot module doesn't support `readwrite` mode, this is part of fio docmentation
> readwrite=str, rw=str
> Type of I/O pattern. Accepted values are:
> -read
> Sequential reads.
> - write
> Sequential writes.
> - trim
> Sequential trims (Linux block devices and SCSI character devices only).
> - randread
> Random reads.
> - randwrite
> Random writes.
> - randtrim
> Random trims (Linux block devices and SCSI character devices only).
> - rw,readwrite
> Sequential mixed reads and writes.
> - randrw
> Random mixed reads and writes.
> - trimwrite
> Sequential trim+write sequences. Blocks will be trimmed first, then the same blocks will be written to.

I don't why only `randrw` is supported, what about support `rw` too ?

**Comment by louwrentius** [comment]
Hello,

There is no good reason why those options are not supported. 

The bad reason is that I myself didn’t use them much and didn’t do the work to test / support them. 

I think that all those options should be supported. Does the current state hurt you in your effort to implement those FS benchmark + graphs? 

Louwrentius

**Comment by Martins3** [comment]
Thanks for your quick reply.

> Does the current state hurt you in your effort to implement those FS benchmark + graphs ?
No, but it confused me from time to time because fio-plot ignores it.
