### ISSUE TITLE
Using devices

### ISSUE THREAD

**Issue by vikramkhatri** [louwrentius/fio-plot#23]
I tested this amazing tool and it works great.

Please consider putting a warning in your README file that if one chooses a device for any "write" operation, they may render the device useless as it will destroy the content of the raw device. But, that is not the case while defining a file as a target that can reside on an NVMe/SSD mounted file system.

**Comment by Martins3** [comment]
Maybe this is the responsibility of fio. But I think whoever does a test with fio can understand what's happening on the raw device when write to them directly.

**Comment by louwrentius** [comment]
Thank you for your feedback. I see your point, but if fio doesn't warn the end-user, why should the benchmark tool? So I agree with Martins3 on this one: I don't think I want to implement this.
