### ISSUE TITLE
filterLogFiles() searchstring bug: read and RANDread data merged

### ISSUE THREAD

**Issue by Nathan-K-Public** [louwrentius/fio-plot#28]
There is a logic bug in L66 in `filterLogFiles()` function. And L50 `searchstring` construction.
Start-of-string delimeter is not used in `if searchstring['searchString'] in item:` . As a result:

- `randread` data is additively merged to `read` data.
- `randwrite` data is additively merged to `write` data.

This corrupts resulting graph by summing data vertically a nondeterministic way. 
Can be visualized by adding `pprint.pprint(logfiles)` at L116 in fio_plot after `logfiles` is declared.

**Comment by Nathan-K-Public** [comment]
Workaround L65 in `filterLogFiles()` function:
`if f"/{searchstring['searchstring']}" in item:`

Tentatively works if path has leading `/` character.
Breaks in trivial case parent path is blank `filename-1-1.log`, so more robust solution needed.

**Comment by louwrentius** [comment]
Thank you for reporting this. I think I have to revisit this whole path parsing thing in light of #20 as it is naive and not robust.

**Comment by louwrentius** [comment]
I believe this commit (to master) resolves the issue. Feel free to re-open this issue if you still observe problems. 

https://github.com/louwrentius/fio-plot/commit/4edfeba1155ee5c06d6bbed0cbc3c5cf159b40ac

Thank you for reporting this problem.
