### ISSUE TITLE
Not able to create comparative graphs

### ISSUE THREAD

**Issue by rahvis** [louwrentius/fio-plot#29]
I am using the latest fio-plot repo

I have 2 Folder:
```
/home/PMEM0_RW_15M/pmem0/1k 
/home/PMEM0_RW_15M/pmem0/4k
```

I want to create a graph comparing these two folders 
`/root/anaconda3/bin/python /root/fio-plot/fio_plot/fio_plot -i /home/PMEM0_RW_15M/pmem0/1k /home/PMEM0_RW_15M/pmem0/4k -T "1K_4K_15_MIN_RANDOM_WRITE" -g -r randwrite -t iops lat -d 1 -n 1 `
![1K_4K_15_MIN_RANDOM_WRITE-2020-08-08_114507](https://user-images.githubusercontent.com/64368687/89714519-e490df00-d9bc-11ea-86b3-d2cbe94c5c88.png)

**Observation**: In the plot above we do not see the Green bar and Orange Bar. Looks missing. 
We only see the blue and red bar. 

Issue: it does not provide the desired result. 

I also tried with renaming the folders as /tmp/A and /tmp/B, but the issue remains the same. 

`/root/anaconda3/bin/python /root/fio-plot/fio_plot/fio_plot -i /tmp/A /tmp/B -T "1K_4K_15_MIN_RANDOM_WRITE" -g -r randwrite -t iops lat -d 1 -n 1`

![1K_4K_15_MIN_RANDOM_WRITE-2020-08-08_121319](https://user-images.githubusercontent.com/64368687/89715056-98e03480-d9c0-11ea-9e08-c5878ed33097.png)

If I plot each folder individually, then it plots as expected (for individual folders)

`/root/anaconda3/bin/python /root/fio-plot/fio_plot/fio_plot -i /home/PMEM0_RW_15M/pmem0/4k  -T "4K_15_MIN_RANDOM_WRITE" -g -r randwrite -t iops lat -d 1 -n 1 `
![4K_15_MIN_RANDOM_WRITE-2020-08-08_114323](https://user-images.githubusercontent.com/64368687/89714565-35a0d300-d9bd-11ea-8fd4-13c158643483.png)

`/root/anaconda3/bin/python /root/fio-plot/fio_plot/fio_plot -i /home/PMEM0_RW_15M/pmem0/1k  -T "1K_15_MIN_RANDOM_WRITE" -g -r randwrite -t iops lat -d 1 -n 1 `
![1K_15_MIN_RANDOM_WRITE-2020-08-08_114312](https://user-images.githubusercontent.com/64368687/89714553-1a35c800-d9bd-11ea-822d-a2418b92d770.png)

Can you please help me in understanding this issue?

**Comment by louwrentius** [comment]
I think you hit #20 and there is a work around discussed there. I will still have to work on a better mechanism but the work around should fix this. (Rename or symlinks)

**Comment by louwrentius** [comment]
Would you mind sharing your data in a zip/tar here? I have made some improvements and I can't reproduce your issue. This may be due to those improvements or maybe there is something else going on.

**Comment by louwrentius** [comment]
I'm assuming this issue is resolved, feel free to reopen this issue if you still have the same problem.

**Comment by rahvis** [comment]
Thanks a lot for resolving the issue.
