### ISSUE TITLE
RFE: correlate commandline arguments with output graphs

### ISSUE THREAD

**Issue by anthonyeleven** [louwrentius/fio-plot#33]
fio-plot is a fantastic tool, thanks for making it available.

As I run a variety of commandlines, output graphs accumulate, and it's easy to lose track of which graph corresponds to which commandline.  This is important for repeatability, as well as to ensure appropriate comparison among block sizes, drive models, etc.

Suggest a commandline flag to aid in this, one option might be to embed the commandline arguments into the output filename.  Another option would be to render the args as text at the bottom of the graph; a third would be to embed the args as a  iTXT or  tEXt string within the PNG file.

Any of these strategies would help unambiguously correlate generation args with the output.

**Comment by louwrentius** [comment]
Thanks for reporting this issue. I have experienced this myself and I think we need something to assure images are generated with the right parameters.

**Comment by anthonyeleven** [comment]
You bet.  To be clear, this isn't a lack of confidence in the generated images, it's housekeeping on the user's part (which would be me :D ).  Typically I collect data and generate graphs on a remote server then scp then down for viewing; with dozens of invocations it's easy to get them mixed up.

**Comment by louwrentius** [comment]
No problem, I understand exactly what you mean. I'll see what I can do.

**Comment by louwrentius** [comment]
I'm writing the metadata to the PNG file using Pillow. https://github.com/louwrentius/fio-plot/commit/318cc8245a30e0e0ab33cb73972051ca40e8858f

Let me know if this works for you. Just update master and you should be able to use it. Also see the readme.

**Comment by Koma-Andrea** [comment]
I'm having the same problem too. To specify the output directory is a must!

Thank you for your work @louwrentius this tool is absolutely fabolous!

**Comment by louwrentius** [comment]
@Koma-Andrea I don't know what you are refering to. I've implemented the desired feature. Feel free to open an issue with your particular request. @anthonyeleven feel free to reopen this issue if it's not to your content.
