### ISSUE TITLE
-t bw option do not render the graph using bandwidth and time

### ISSUE THREAD

**Issue by swaroopv2** [louwrentius/fio-plot#36]
-t bw option do not render the graph using bandwidth and time. Instead it generates a graph again using IOPS and latency. I made sure that the log file names are following the exact naming convention required.

**Comment by louwrentius** [comment]
Can you share the entire commandline used?

**Comment by swaroopv2** [comment]
> Can you share the entire commandline used?
> […](#)
> On 1 Oct 2020, at 20:39, swaroopv2 ***@***.***> wrote: ﻿ -t bw option do not render the graph using bandwidth and time. Instead it generates a graph again using IOPS and latency. I made sure that the log file names are following the exact naming convention required. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

sure. Here it is.Sorry for giving you only half information.

[root@ops-script fio_plot]# ./fio_plot -i /mnt/disk1/vm_benchmarks/L32s -T "Azure-VM-NVMe-Sequential-Reads-L32s" -l --enable-markers -t bw -d 8 -n 2 -r read

logs directory filenames:
-rw-r--r--. 1 root root 12470 Sep 30 09:01 read-iodepth-8-numjobs-2_bw.1.log
-rw-r--r--. 1 root root 12471 Sep 30 09:01 read-iodepth-8-numjobs-2_bw.2.log
-rw-r--r--. 1 root root 11913 Sep 30 09:01 read-iodepth-8-numjobs-2_clat.1.log
-rw-r--r--. 1 root root 11913 Sep 30 09:01 read-iodepth-8-numjobs-2_clat.2.log
-rw-r--r--. 1 root root 12458 Sep 30 09:01 read-iodepth-8-numjobs-2_iops.1.log
-rw-r--r--. 1 root root 12458 Sep 30 09:01 read-iodepth-8-numjobs-2_iops.2.log
-rw-r--r--. 1 root root 11914 Sep 30 09:01 read-iodepth-8-numjobs-2_lat.1.log
-rw-r--r--. 1 root root 11913 Sep 30 09:01 read-iodepth-8-numjobs-2_lat.2.log
-rw-r--r--. 1 root root 11292 Sep 30 09:01 read-iodepth-8-numjobs-2_slat.1.log
-rw-r--r--. 1 root root 11292 Sep 30 09:01 read-iodepth-8-numjobs-2_slat.2.log

**Comment by louwrentius** [comment]
The -g graph uses .log files for generating graphs. You are using the -l option (2d bars). Use -g and it should work.

**Comment by swaroopv2** [comment]
Thanks it worked like a charm.
