### ISSUE TITLE
Graphs skewed when comparing more than 4 attributes

### ISSUE THREAD

**Issue by swaroopv2** [louwrentius/fio-plot#37]
Hello, I see you have a 2d picture where you are able to plot 7 iodepths in single chart. I am trying to plot a graph that shows IOPS/Latency for 6 different VM sizes and the graph looks very skewed and abnormally long. 

Could you let us know how to play with the graph sizing.

Here is the command i am using.

./fio_plot -i /dir1 /dir2 /dir3 /dir4 /dir5 /dir6 -T "Read-iodepth" -C -r read -n 2 -d 8

**Comment by louwrentius** [comment]
Could you share the benchmark data in a zip file (you can just drop it in this issue). I've not yet tested the compare feature with six datasources.

**Comment by louwrentius** [comment]
I've tried to reproduce the issue and tested with six directories and the graph was fine. I'm closing this issue, but feel free to reopen it and supply the test data used to reproduce the bug.
