### ISSUE TITLE
Provide command-line commands for the example graphs in the README.md

### ISSUE THREAD

**Issue by rubin55** [louwrentius/fio-plot#38]
It would be nice for the budding fio-plot user to see the commandline for how the example graph came to be. New users will then quickly get up to speed with the utility, including how to set title, subtitle, how to combine graphs, etc.

**Comment by louwrentius** [comment]
Thanks for your feedback. Would you mind pointing out exactly which examples should be expanded upon? The subtitle option doesn't have an example, so that's a good one. The combine graph option does have examples, what is unclear about those?

**Comment by rubin55** [comment]
Essentially, any graph-picture in the README.md, there are quite a few. I would put the command used to generate said graph underneath the picture so people can quickly try it and see the same results (albeit for their own systems).

The first combined graph picture does not have command line examples, if I scroll down about two-thirds, I do see a combined graph picture with command.

I guess, because the readme is quite large, I tend to look for more systematic information (i.e., every picture has the associated command used to generate it): you start reading from the top and see a graph and intuitively immediatly ask yourself: how is that one done.

**Comment by louwrentius** [comment]
Thank you, I understand your point.

**Comment by louwrentius** [comment]
I have done exactly as you proposed, since some graphs were already a bit out-dated. Feel free to reopen this issue if you see fit.
