### ISSUE TITLE
Bad graph layout when comparing multiple queue depth and jobs

### ISSUE THREAD

**Issue by rubin55** [louwrentius/fio-plot#40]
`fio_plot -i "raaf/think/4k" --title "raaf/think" --subtitle "4k block (random read iops)" --dpi
 300 -l -t iops -r randread -d 1 2 4 8 16 32 -n 1 2 4 8 16 32`

Results in:
![raaf-think_2020-10-27_183017](https://user-images.githubusercontent.com/6214491/97339146-85878b80-1882-11eb-8b2f-14e2b6958093.png)

Ergo, the graph is strangely aligned to the right + other parts of the tables overlap.

**Comment by rubin55** [comment]
PS: Sorry for the issue onslaught, please see it as a compliment, fio_plot is great!

**Comment by louwrentius** [comment]
Ha, that is a good one, you should not be able to specify multiple numjobs with this graph type :-)

Thank you for these issues, I’m totally happy that you report them!

**Comment by louwrentius** [comment]
Thank you for reporting this issue. I've just pushed some fixes to master. I'm closing this issue but if you believe something is still wrong, feel free to reopen it.
