### ISSUE TITLE
[Feature Request] SSD Preconditioning

### ISSUE THREAD

**Issue by sjh5205** [louwrentius/fio-plot#42]
As I know, if we want to get reliable result, before running benchmark we should prepare SSD.
It is usually called 'SSD Preconditioning'.

benchmark_script within fio-plot is fancy tool, but It doesn't contains preconditioning option.
So, I run my preconditioning shell script first before executing fio-plot's benchmark script.

I think it is more convenient when SSD preconditioning is integrated with fio-plot's benchmark script.

**Comment by louwrentius** [comment]
What kind of precondition do you run? Can you share the script or command(s)?

**Comment by sjh5205** [comment]
Here is preconditioning script. from [fiovisualizer](https://github.com/intel/fiovisualizer/tree/master/Workloads/Precondition)

`dd if=/dev/zero bs=1024k of=/dev/nvme0n1` (run twice)

**fio config**
```[global]
name=4k random write 4 ios in the queue in 32 queues
filename=/dev/nvme0n1
ioengine=libaio
direct=1
bs=4k
rw=randwrite
iodepth=4
numjobs=32
buffered=0
size=100%
loops=2
randrepeat=0
norandommap
refill_buffers

[job1]
```

**Comment by louwrentius** [comment]
Thanks, I will look into this.

I am aware that pre-zeroed SSD are faster and if you want to test that, I understand the need. 

It needs to be incorporated into my script because it needs to run this after each benchmark. 

I see the benefit of incorporating this!

I should look more at fiovisualiser and learn a bit more about their testing options. Maybe there are other things like this I should address.

**Comment by louwrentius** [comment]
I'm working on this issue. Right now, the precondition run is run once. Then, multiple benchmarks are run (as specified). 

The most important thing is that the entire device is written twice, as I understand it. I don't think it's required to run a preconditioning run after every single benchmark.

Furthermore: it seems that Fio has a build-in option to detect and determine steady-state. I'm adding this option to the bench_fio script. Fio stores benchmark data in .json format in a special section called 'steadystate' in addition to the log data.

Some testing shows that it works as advertised: if steady state is achieved, the benchmark is stopped before the runtime is over. If the device (n)ever achieves steady-state, this is recorded in the 'attained' key. 

I'm planning to see how to deal with this information and this may also require updates to fio_plot.

**Comment by louwrentius** [comment]
@sjh5205 you may have moved on and this feature is no longer relevant to you. But I did implement the feature. It's now possible to run a preconditioning run before the actual benchmarks run. But you can also repeat the preconditioning run after each individual benchmark.
