### ISSUE TITLE
[Feature Request] To be able to create a 3D chart to chart bandwidth

### ISSUE THREAD

**Issue by zapbranighan** [louwrentius/fio-plot#44]
Hi,

Would it be possible to add a feature to create a 3D chart to chart bandwidth (not just IOPs and latency)

Thanks,
Zap

**Comment by zapbranighan** [comment]
To be more specific, from the example in README.md, I would like to create a 3D bandwidth gap with the following command:
`~/projects/fio-plot/fio_plot/fio_plot -i RAID10 --source "https://louwrentius.com"  -T "RAID10 performance of 8 x WD Velociraptor 10K RPM" -L -t bw -r randread`

**Comment by louwrentius** [comment]
That should not be that big of a deal, I’ll look into it.

**Comment by louwrentius** [comment]
For what it's worth, I have this feature implemented, but not yet in the master branch. Just to give you an update.

**Comment by zapbranighan** [comment]
Great! I can’t wait to try it once you merge the changes to master.

**Comment by louwrentius** [comment]
I've merged the feature into master.
