### ISSUE TITLE
[feature request] include fio version on graphs

### ISSUE THREAD

**Issue by sitsofe** [louwrentius/fio-plot#48]
https://github.com/axboe/fio/blob/master/MORAL-LICENSE encourages people publishing benchmarks to mention they used fio and which version it was. Would it be possible for you to add that information to graphs your tool makes? If so would you also consider an opt-out option too? The hope is that it would help people consuming the graphs too (e.g. fio has bugs that get fixed over time so it's good to know the version etc)...

**Comment by louwrentius** [comment]
Fair enough, should not be too hard.

**Comment by louwrentius** [comment]
@sitsofe I can add the version to certain graphs, but the line graphs I showed in that bug report I made, can't display the Fio version because that data does not exist in the log files. 

The only way to do so, would be to assume that there is an accompanying .json file which name I can predict. This is actually the case when my bench_fio script was used to generate the benchmark data. So I could put that in. But if no predictable .json name is found, the Fio version will be omitted from this particular graph type.

**Comment by sitsofe** [comment]
@louwrentius FYI: I think the fio version may turn up in `terse` logs too but that likely doesn't help you.

I would add the fio version when you know it otherwise leave it out and just mention something like "Data from fio, graphed by fio-plot 1.0.7" (or some better wording :-) when the user doesn't tell you a version. I guess the key will be having an option to manually say the fio version and having an option to disable adding that text entirely...

**Comment by louwrentius** [comment]
The Fio version is now displayed in all _graph_ types. I've implemented it the 'hard' way as proposed. So if .json files are available, they are processed and the Fio version is shown. If no .json files are found, no version is displayed (it can't). 
The version can be disabled with --disable-fio-version

It looks like this: 

![Comparing-performance-of-multiple-SSDs_2020-12-13_153207](https://user-images.githubusercontent.com/1312044/102014888-9c157380-3d58-11eb-8190-522776c7b69f.png)
![Comparing-the-performance-of-various-Solid-State-Drives_2020-12-13_153202](https://user-images.githubusercontent.com/1312044/102014890-9ddf3700-3d58-11eb-8b8e-99c76f42e28f.png)

I think this closes out the request, feel free to reopen the issue if required.

**Comment by louwrentius** [comment]
I forgot to implement your proposal to display "Data generated by Fio" if the Fio version is not available.

**Comment by louwrentius** [comment]
![No- json-files-so-no-Fio-version_2020-12-13_154530](https://user-images.githubusercontent.com/1312044/102015175-3e822680-3d5a-11eb-9b39-cdf6976b2e23.png)

**Comment by sitsofe** [comment]
(I feel slightly aggrieved that when the fio version is available we don't get to see a shout out to fio-plot which is also working hard to produce those graphs... but no matter what you choose to do thanks for considering this change!)
