### ISSUE TITLE
Support of rbd ioengine fio test

### ISSUE THREAD

**Issue by efazenda** [louwrentius/fio-plot#52]
Hi, 

We are using your tool and it is very helpful four our tests, but we wanted to know if we could have the support of the ioengine **rbd**.

As in the template fio we can setup the following 

```
[iotest]
ioengine=rbd
pool=pool_ssd
rbdname=test
rw=${MODE}
blocksize=${BLOCK_SIZE}
iodepth=${IODEPTH}
numjobs=${NUMJOBS}
direct=${DIRECT}
group_reporting=1
invalidate=${INVALIDATE}
loops=${LOOPS}
write_bw_log=${OUTPUT}/${MODE}-iodepth-${IODEPTH}-numjobs-${NUMJOBS}
write_lat_log=${OUTPUT}/${MODE}-iodepth-${IODEPTH}-numjobs-${NUMJOBS}
write_iops_log=${OUTPUT}/${MODE}-iodepth-${IODEPTH}-numjobs-${NUMJOBS}
log_avg_msec=${LOGINTERVAL}
```

When running the command bench_fio we have the --target and --type mandatory, but actually in the rbd settings for fio it is not needed.

Is this could be implemented ? 

Maybe I have an misunderstanding of the --device --type options in case of using rbd ioengine.

Coudl you please help me with this ? 

Thank You !

Best Regards, Edouard Fazenda.

**Comment by louwrentius** [comment]
Hi, I happen to have a working Ceph cluster somewhere I think. 

I'll take a look what I can do maybe in the comming days.

With Ceph, my current experience is that you can count the IOPs by hand and the I/O latency with a stopwatch but I guess there are people with better hardware I suppose.

**Comment by efazenda** [comment]
Hi, 

Thanks for the quick feedback and for having a look :) !
It would help us a lot :) 

Have a nice day !

Best Regards, Edouard Fazenda.

**Comment by louwrentius** [comment]
Would you mind testing the 'rbd' branch? 

This command seems to work for me on my cluster: 

`./bench_fio` --target test01 --type rbd -o ceph --ceph-pool rbd --template fio-job-template-ceph.fio

**Comment by louwrentius** [comment]
No response means everything is OK. Merged with master branch.
