### ISSUE TITLE
junk files in git

### ISSUE THREAD

**Issue by draeath** [louwrentius/fio-plot#53]
Hello,

While trying out your project, I noticed you have some stuff in your repo that should ideally be put into .gitignore and never added.

Notable examples are the OSX .DS_Store files and \_\_pychace__ directories.

Consider removing these files (they're small enough you don't have to go back rewriting history to wipe them!) and utilizing a good .gitignore. [This](https://github.com/github/gitignore/blob/master/Python.gitignore) might be a good one to base from!

**Comment by draeath** [comment]
I see you've got some of them ignored, but since they were tracked before you added that they're still, uh, tracked. :)

Also looks like `.vscode` and `.pytest_cache` should be similarly treated.

**Comment by louwrentius** [comment]
Thanks for your contribution!

I have cleaned up the .DS_Store and __pychache__ files. 
I want to keep the vscode files, I'm not going to remove them. 

I've pushed the cleanup to the  master branch.
