### ISSUE TITLE
bench_fio: 'size' argument unit is not specified

### ISSUE THREAD

**Issue by draeath** [louwrentius/fio-plot#54]
Hello,

What unit is the 'size' argument? This should be detailed in the argparser description.

**Comment by draeath** [comment]
It appears this is passed through to `fio` and follows the following:

    SI integer:
      a whole number, possibly containing a suffix denoting the base unit of the value.
      Accepted suffixes are `k', 'M', 'G', 'T', and 'P', denoting kilo (1024), mega (1024^2), giga (1024^3), tera (1024^4), and peta (1024^5) respectively.
      If prefixed with '0x', the value is assumed to be base 16 (hexadecimal).
      A suffix may include a trailing 'b', for instance 'kb' is identical to 'k'.
      You can specify a base 10 value by using 'KiB', 'MiB','GiB', etc. This is useful for disk drives where values are often given in base 10 values. Specifying '30GiB' will get you 30*1000^3 bytes.
      The suffixes are not case sensitive. 

I'm not sure how that would distill down, but perhaps it's sufficient just to note that the parameter is fed to 'fio'

**Comment by louwrentius** [comment]
Yes, I was assuming that people understand all arguments in the context of Fio itself, because they are all passed to Fio. But I've altered the help text and pushed this to master.
