### ISSUE TITLE
-t bw not working

### ISSUE THREAD

**Issue by bhelm** [louwrentius/fio-plot#57]
I try to generate a read bandwidth comparison graph, but always get a iops graph. Is this an error in the tool or is there something wrong with my command? (using the git master).

Thank You.

```
@rescue ~/fio-plot/benchmark_script # ../fio_plot/fio_plot -i plain/sd*/* -T "SegRead" -C -r read -t bw lat -n 4 -d 32

 Saving to file SegRead_2021-04-26_201149_Nz.png
```
![SegRead_2021-04-26_201149_Nz](https://user-images.githubusercontent.com/769791/116130672-cba39780-a6cb-11eb-99bb-98daa551455c.png)

my data was generated with
```
~/fio-plot/benchmark_script # ./bench_fio --target /dev/sda2 /dev/sdb2 /dev/sdc2 /dev/sdd2 --type device --mode read write -b 1024k --output plain --direct=1 --numjobs 4 --runtime 10 --iodepth 32
```

**Comment by louwrentius** [comment]
The -t patameter does only work with -g graphs and not with -C graphs. The -g graph will allow you to make your comparison.

**Comment by louwrentius** [comment]
I have committed this improvement to master. Let me know if everything works out for you.

**Comment by bhelm** [comment]
Ok, thank you for the clarification!

I wanted these BW graphs so i made them possible, hopefully without breaking anything. see https://github.com/louwrentius/fio-plot/pull/58
