### ISSUE TITLE
--max-iops and --max-latency options don't work for 2D bar chart style graphs (-C and -l)

### ISSUE THREAD

**Issue by jsrolon** [louwrentius/fio-plot#71]
Hello, I am trying to get multiple comparison graphs to have the same ranges on their y-axes. I am plotting one comparison graph per `numjobs` value. I thought that I could accomplish this by using `--max-iops` and `--max-latency`, as in:

```
fio-plot -i libaio uio_pci_generic vfio-pci -T "Dell P4800X SSD" -C -r randrw -f write --numjobs 16 --max-lat 40 --max-iops 300000
```

Since my latency values range from 9 to 32 us or so in all cases. What happens now is that every graph has its own y-axis value range, making it hard to do comparisons between `numjob` values hard with quick glances.

Any command line options for this, or should I modify the plotting code?

Thanks!

**Comment by louwrentius** [comment]
Hi, I’m not sure exactly what is going on. Could you also share the files so I can reproduce this? Can share them by mail if you want (louwrentius at gmail dot com) 

With regards

**Comment by louwrentius** [comment]
The answer to your problem is for 99% due either bad documentation or me not implementing things consistently.

I've grepped through the code and the --max-lat --max-iops parameters don't work for this graph type (2d bar chart), it was only implemented for 3D bar charts and -g style graphs.
