### ISSUE TITLE
Type 'directory' with multiple targets will result in single result

### ISSUE THREAD

**Issue by haniffm** [louwrentius/fio-plot#74]
When running the `bench-fio` with `--type directory` and multiple mounted disks e.g. `--target /mnt/sdb /mnt/sdc` only results from one of them are stored in the `--output` directory.

Running with git commit hash: f45eebaf12b7e2fe5f0b9cc5c75ed659e1b4c53f

To reproduce:
- Given you have at least 2 mounted devices at `/mnt/sdb` and `/mnt/sdc`
- Run the following:
```
./bin/bench-fio --target /mnt/sdb/ /mnt/sdc/ --type directory --output out_dir --size 128MB --template ./bench_fio/templates/fio-job-template.fio --numjobs 1 --iodepth 1 8 64 --runtime 3
```

The output looks something like this:
```
out_dir
└── 4k
    ├── randread-1-1.json
    ├── randread-64-1.json
    ├── randread-8-1.json
    ├── randread-iodepth-1-numjobs-1_bw.1.log
    ├── randread-iodepth-1-numjobs-1_clat.1.log
    ├── randread-iodepth-1-numjobs-1_iops.1.log
    ├── randread-iodepth-1-numjobs-1_lat.1.log
    ├── randread-iodepth-1-numjobs-1_slat.1.log
    ├── randread-iodepth-64-numjobs-1_bw.1.log
    ├── randread-iodepth-64-numjobs-1_clat.1.log
    ├── randread-iodepth-64-numjobs-1_iops.1.log
    ├── randread-iodepth-64-numjobs-1_lat.1.log
    ├── randread-iodepth-64-numjobs-1_slat.1.log
    ├── randread-iodepth-8-numjobs-1_bw.1.log
    ├── randread-iodepth-8-numjobs-1_clat.1.log
    ├── randread-iodepth-8-numjobs-1_iops.1.log
    ├── randread-iodepth-8-numjobs-1_lat.1.log
    ├── randread-iodepth-8-numjobs-1_slat.1.log
    ├── randwrite-1-1.json
    ├── randwrite-64-1.json
    ├── randwrite-8-1.json
    ├── randwrite-iodepth-1-numjobs-1_bw.1.log
    ├── randwrite-iodepth-1-numjobs-1_clat.1.log
    ├── randwrite-iodepth-1-numjobs-1_iops.1.log
    ├── randwrite-iodepth-1-numjobs-1_lat.1.log
    ├── randwrite-iodepth-1-numjobs-1_slat.1.log
    ├── randwrite-iodepth-64-numjobs-1_bw.1.log
    ├── randwrite-iodepth-64-numjobs-1_clat.1.log
    ├── randwrite-iodepth-64-numjobs-1_iops.1.log
    ├── randwrite-iodepth-64-numjobs-1_lat.1.log
    ├── randwrite-iodepth-64-numjobs-1_slat.1.log
    ├── randwrite-iodepth-8-numjobs-1_bw.1.log
    ├── randwrite-iodepth-8-numjobs-1_clat.1.log
    ├── randwrite-iodepth-8-numjobs-1_iops.1.log
    ├── randwrite-iodepth-8-numjobs-1_lat.1.log
    └── randwrite-iodepth-8-numjobs-1_slat.1.log

```

Note that this works fine when using `--type device` with multiple devices. There will be one sub directory for each device. I think that should work the same way when using `--type directory`.

**Comment by chenyuanrun** [comment]
Multiple file type targets have this issue too:
`target = /vol1/50G,/nfs-vol1/50G`
The output of second target is overwrite by the first target.

**Comment by chenyuanrun** [comment]
> Multiple file type targets have this issue too: `target = /vol1/50G,/nfs-vol1/50G` The output of second target is overwrite by the first target.

Ok, that is my fault.
https://github.com/louwrentius/fio-plot/blob/d3e20a15d9a10079fb0ab81467c395d05eabdf0f/bench_fio/benchlib/supporting.py#L49C34-L49C40
show that bench-fio use the base name of target as direcotory, output directory will be overwrite if two targets have the same base name.
