### ISSUE TITLE
Read CSV output

### ISSUE THREAD

**Issue by alicefr** [louwrentius/fio-plot#75]
Hi, I've the fio output in CSV format (default generated output format). I've tried to compare 2 dataset but I get:
```bash
$ fio-plot -C -i output-fio-vm-test output-fio-pod-test  -T "Random read with device test"  -r read

Could not find any (matching) JSON files in the specified directory /home/afrosi/go/src/github.com/alicefr/kubevirt-test/output-fio-pod-test/output

Are the correct directories specified?

If so, please check the -d ([1]) -n ([1]) and -r (read) parameters.
```
Can we directly use the CSV format or do I necessarily need to convert the output in json. If so, can you suggest any tools?

**Comment by louwrentius** [comment]
Sorry for the 3+ month late reply. As you may have realised by now you can only compare using the .json output. A more indirect way to compare, using the .log (csv) output is to use the -g option to graph lines of the measured values during the run.
