### ISSUE TITLE
Pre condition just reads the device

### ISSUE THREAD

**Issue by mtnredhed** [louwrentius/fio-plot#76]
The precondition step seems to just read the device, never writes it and never moves on to the the other tests.

thanks for looking at this. 

                                             +++ Fio Benchmark Script +++

Estimated duration            : 1:38:00
Test target                   : /dev/nvme0n1
Job template                  : /usr/local/lib/python3.8/dist-packages/bench_fio/benchlib/../templates/fio-job-template.fio
I/O Engine                    : libaio
Test mode (read/write)        : randread randwrite
IOdepth to be tested          : 1 2 4 8 16 32 64
NumJobs to be tested          : 1 2 4 8 16 32 64
Block size                    : 4k
Direct I/O                    : 1
Run precondition workload     : True
Precondition template         : precondition.fio
Benchmark entire device       : True
Time duration per test (s)    : 60
Benchmark loops               : 1
Log interval of perf data (ms): 500
Invalidate buffer cache       : 1
Target type                   : device
Output folder                 : bench-fio
Number of benchmarks          : 98

[precondition]
name=1m
ioengine=libaio
direct=1
bs=1m
rw=write
iodepth=64
numjobs=1
buffered=0
size=100%
loops=2
randrepeat=0
norandommap=1
refill_buffers=1
write_bw_log=${OUTPUT}/${MODE}-iodepth-1-numjobs-8
write_lat_log=${OUTPUT}/${MODE}-iodepth-1-numjobs-8
write_iops_log=${OUTPUT}/${MODE}-iodepth-1-numjobs-8
log_avg_msec=${LOGINTERVAL}

bench-fio -d /dev/nvme0n1 -t device --precondition --entire-device -o /root/bench-fio

It sat reading the device for over 2 hours. (7.68T nvme drive)

```
Device             tps    kB_read/s    kB_wrtn/s    kB_dscd/s    kB_read    kB_wrtn    kB_dscd
nvme0n1       110053.60    440214.40         0.00         0.00    2201072          0          0
```

It also wrote an empty /root/bench-fio/nvme0n1/4k/randread-1-1.json file

**Comment by mtnredhed** [comment]
ok, I think I realize what happened. "--entire-device" overrules the time duration per test.  It still doesn't seem like precondition is being run.

**Comment by louwrentius** [comment]
There was an obvious bug in the code where the preconditioning was only run if precondition-repeat was also set. I think it's fixed now, it seems to be fine on my test system.
