### ISSUE TITLE
Output Filename always generated

### ISSUE THREAD

**Issue by baurmatt** [louwrentius/fio-plot#83]
https://github.com/louwrentius/fio-plot/blob/2ed57953309a63fce644d4c8d810928dc9e68809/fio_plot/fiolib/supporting.py#L402

Due to `len(settings["output_filename"]) > 0`, the filename gets always generated. I guess it should it `len(settings["output_filename"]) == 0`

**Comment by louwrentius** [comment]
This one is fixed by #85
