### ISSUE TITLE
Precondition does not fullfill the ssd/nvme capacity 

### ISSUE THREAD

**Issue by letonphat1988** [louwrentius/fio-plot#84]
I saw the precondition's fio process was running base on runtime not on capacity which defined 100% in template. BTW precondition in my knowledge need one more 4K randwrite job 

prefer document: https://github.com/intel/fiovisualizer/blob/master/Workloads/Precondition/SSD%20precondition.txt

**Comment by louwrentius** [comment]
Sorry for the very late reply.
Hi, I've taken a look at the fio template and the code, I don't see the issue. Can you show me somewhay what is going wrong?

**Comment by jackeichen** [comment]
I think it is a code mistake, @louwrentius  you set a settings_copy but used the old workload setting.
