### ISSUE TITLE
Can't find matching JSON file

### ISSUE THREAD

**Issue by cross-cisco** [louwrentius/fio-plot#87]
Apologies for putting this here, if there is a community space or mailer, let me know.

I am trying to use fio-plot to compare outputs from multiple systems.  But whatever I do, I'm getting the well-known 
`Could not find any (matching) JSON files in the specified directory`

At first this was because I wasn't using any of -d, -n, or -r.  That was fixed quickly enough.  But, now I'm still seeing it.

The fio command I'm running is:
`fio --filename=/Volume/7.0.5-72/tmp/fio-file --size=500GB --direct=1 --rw=randrw --bs=16k --ioengine=libaio --iodepth=64 --runtime=300 --numjobs=4 --time_based --group_reporting --name=throughput-test-job --eta-newline=1 --output-format=json+ --output=system1.json`
(and to `system2.json` on another system)

I'm then running fio-plot as:
`fio-plot -i /var/tmp/cross2/fio-output/* --source "https://louwrentius.com" -T "Comparing the performance of" -C -d 64 -n 4 -r randrw --xlabel-parent 0`

That _seems_ right, but I get:
```
Could not find any (matching) JSON files in the specified directory /var/tmp/cross2/fio-output/system1

Are the correct directories specified?

If so, please check the -d ([64]) -n ([4]) and -r (randrw) parameters.

```

(/var/tmp/cross2/fio-output/system1 is a directory containing only the `system1.json` from above(

**Comment by louwrentius** [comment]
Hi, at the bottom of the README you can find the segment "JSON / LOG file name requirements".

Your JSON file must be named like randread-1-1.json or something similar. Those numbers are iodepth and numjobs.

Hope this helps, let me know if this works.

**Comment by cross-cisco** [comment]
Thanks.  `randrw-16-4.json` doesn't work, but I was being too literal.  Looking at the readme I see more is required.  I presume that since I have only one run per system that I'm comparing, `[numbjob job id]` should always be 1 on my one file for each?
I'll have a chance to try this in a few hours.

**Comment by cross-cisco** [comment]
Alright.  I've spent a lot of time trying this, and looking into fiolib/jsonimport.py.  Regardless of the filename, it seems to fail to parse the json as valid.  It looks like it's confused by the structure.
I'm using fio-3.33.  I'm not sure if it might've changed the json format at some point?

**Comment by louwrentius** [comment]
Sorry to hear that. Would you be willing/able to share the json file with me?  I can try and fix the issue.

**Comment by cross-cisco** [comment]
Sure.  Let me get that to you.  For context, I started by using [fio-rand-RW.fio](https://github.com/axboe/fio/blob/master/examples/fio-rand-RW.fio).  But, after working through the first couple parsing issues, `fio-plot` gave me a "sorry, I can't handle more than 1 job".  So I modified fio-rand-RW.fio to set numjobs to 1 and ran `fio` with that.

Attached are the output of that run in json and json+ output formats.  (I tried both, same errors)
[jupiter.fio-rand-RW.json.txt](https://github.com/louwrentius/fio-plot/files/10494267/jupiter.fio-rand-RW.json.txt)
[jupiter.fio-rand-RW.json+.txt](https://github.com/louwrentius/fio-plot/files/10494269/jupiter.fio-rand-RW.json%2B.txt)

**Comment by louwrentius** [comment]
I'm currently taking a look

**Comment by louwrentius** [comment]
I think I have fixed the issue. New code is committed to master branch and also to pypi.
The filename should be - in this case - randrw-16-1.json 

The command you issued however requires at least two different benchmark results you want to compare so the -i parameter needs two separate folders, like the Readme Example: fio-plot -i INTEL_D3-S4610 SAMSUNG_860_PRO KINGSTON_DC500M SAMSUNG_PM883

It could also look like this is the bench_fio tool is used for testing. 
-i test1/4k/randrw-1-16.json test2/4k/randrw-1-16.json

However, this is a side note. I just generated a different graph myself like this:

fio-plot -i ./result/4k --source "https://louwrentius.com" -T "Test" -l -r randrw -d 16 -n 1 -f read

 Saving to file Test_2023-01-25_004257_Uj.png

Notice the -f read (or -f write) option. The output graph makes less sense as normally you have a range of tests with different numjobs/iodepth parameters, so you get multiple columns but at least it works, the JSON is properly parsed.

![Test_2023-01-25_004257_Uj](https://user-images.githubusercontent.com/1312044/214445871-f303b7b8-18a8-40db-ab2d-db411c879b9d.png)

**Comment by cross-cisco** [comment]
Thank you.  With one change that worked.  (`dict | dict` isn't supported until python 3.9. I'd already written code to do that thought so just moved it.  Let me know if you want a PR, but it's just:
`
                 if "global options" in candidate_json.keys():
-                    job_options = candidate_json["jobs"][0]["job options"] | candidate_json["global options"]
+                    job_options = candidate_json["jobs"][0]["job options"]
+                    job_options.update(candidate_json["global options"])
                 else:
                     job_options = candidate_json["jobs"][0]["job options"]

`

I have a couple other questions about how best to get data for this, but that's separate from this bug.
Sadly, I can't use bench-fio to run these tests, because I'm running fio on something only slightly above an embedded system, so putting python modules on it would be non-trivial.
Does bench-fio have the ability to generate the list of fio commands it wants to run?  If so I could do that and move the output back to the system with fio-plot on it.

**Comment by louwrentius** [comment]
Doh, forgot to check the Python version, so I'm incorporating your change and create an updated version. I'm fine if you also use this issue for other discussion.

Regarding your question about bench-fio. 

Option 1: what you proposed: bench-fio would spit out a list of fio commands, based on command-line parameters. 
Option 2: would be similar but we generate .fio files containing hard-coded arguments for each test and use those as arguments. 

The key issue however is that currently we use the .fio template and define the variables using the environment. So both options would require quite a bit of changes. 

Option 3: to use the client-server mechanism of Fio. https://fio.readthedocs.io/en/latest/fio_doc.html#client-server

If I have ever tried/tested this feature, I've totally forgotten about it, but the manual is quite straightforward. You would run the 'server' on the embedded device with the storage to be tested. The client is run from your computer with bench-fio installed. 

Now I am actually interested if we can make this work but I can't promise anything at any timeframe. I have to test the client/server, I have to change and test the code. 

For you, the quick-and-dirty method is to edit the file runfio.py in the benchlib directory. You need to alter the run_fio function, in particular this segment:

`    command = [
        "fio",
        "--output-format=json",
        f"--output={output_file}",
        settings["template"],
    ]`

Maybe you can try and just hard-code the server address in here like this:

    command = [
        "fio",
       "--server 192.168.123.128",
        "--output-format=json",
        f"--output={output_file}",
        settings["template"],
    ]

That said, I have zero experience with fio client/server so not sure if this is going to work.

**Comment by louwrentius** [comment]
Feel free to re-open this ticket if there is any related issue.
