### ISSUE TITLE
[fio-plot] Only randwrite is drew when plot randrw workload

### ISSUE THREAD

**Issue by jackeichen** [louwrentius/fio-plot#94]
I test randrw(read/write=7/3), but only randwrite is drew. Here is my commandline:

`fio-plot -i tt/ --source "Performance Test" -T "SAMSUNG PM9A3 4k mix randrw(RW=7:3)" -g -t iops -r randrw --xlabel-parent 0 -d 32 -n 4`

And I wish there would be 3 lines in picture: read iops,write iops,total iops

![SAMSUNG-PM9A3-4k-mix-randrw(RW=7_3)_2023-01-31_030834_HG](https://user-images.githubusercontent.com/20065172/215703128-d52c57f1-2343-4afd-a215-ae77750816e7.png)

**Comment by louwrentius** [comment]
Hi, sorry to see that. I can confirm with  my own test. 

![TEST_2023-01-31_102206_Uw](https://user-images.githubusercontent.com/1312044/215720153-31c29e7b-3a22-433f-b346-386cb4cd6aaa.png)

I will take a look

**Comment by louwrentius** [comment]
The issue is that the y-axis limit is calculated wrong, so your 'blue' line for the reads falls off the chart. 
Below the limit is hard-coded to include all data. 

![TEST_2023-01-31_104334_zK](https://user-images.githubusercontent.com/1312044/215724795-856b5afa-8995-4ad4-b4ce-90d1f5bf3bff.png)

**Comment by louwrentius** [comment]
`And I wish there would be 3 lines in picture: read iops,write iops,total iops`

Can you make a separate feature request for that?
