### ISSUE TITLE
Request to add total IOPS for randrw workload in fio-plot

### ISSUE THREAD

**Issue by jackeichen** [louwrentius/fio-plot#96]
Usually a total IOPS is indicated in PCIe SSD's spec, it becomes more convenient to compare the performance between the test result and spec value.

![1675166849641](https://user-images.githubusercontent.com/20065172/215755682-58b6fe77-f58c-4d64-bf0e-2959209a3a7a.png)

**Comment by louwrentius** [comment]
I have build this new feature in a separate branch "total".
Do a git pull and then git checkout total should work. 

There is a new option --draw-total that works with -g style graphs. It only works with randrw benchmark data. The -f (filter) parameter defaults to 'read write' which is what we want but you can set it explicitly.

I had a folder with benchmark data and ran this command:

`fio-plot -i . -T "TEST" -r randrw -g -t iops --draw-total`

![TEST_2023-02-01_003055_VJ](https://user-images.githubusercontent.com/1312044/215907553-2c075f89-f4f4-4fba-9252-11520d3c5181.png)

I don't have a way to 'only' draw the total and not the separate read / write data but at least we have a total. If there's any feedback it's welcome.

**Comment by jackeichen** [comment]
Thanks for the improvement!
